{% set version = "0.9.4" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-wk
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/wk_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/wk/wk_{{ version }}.tar.gz
  sha256: b973dd5fa9aed94efc7ea4027146e804ba54df818a71278d6a5b7df0ae9e348b

build:
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-cpp11                      # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-cpp11
  run:
    - r-base
    - r-cpp11

test:
  commands:
    - $R -e "library('wk')"           # [not win]
    - "\"%R%\" -e \"library('wk')\""  # [win]

about:
  home: https://paleolimbot.github.io/wk/
  dev_url: https://github.com/paleolimbot/wk
  license: MIT
  summary: Provides a minimal R and C++ API for parsing well-known binary and well-known text representation of geometries to and from R-native formats. Well-known binary is compact and fast to parse; well-known text is human-readable and is useful for writing tests. These formats are only useful in R if the information
    they contain can be accessed in R, for which high-performance functions are provided here.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
